### ISSUE TITLE
https connection & secure option

### ISSUE THREAD

**Issue by msmart** [dound/gae-sessions#10]
Hi, shouldn't the secure option be set when a https connection is used (e.g. https://myapp.appspot.com)?

**Comment by dound** [comment]
What do you mean by "the secure option"?

**Comment by msmart** [comment]
Sorry for being unclear. A server can specify the secure flag while setting a cookie; the browser will then send it only over a secure channel, such as an SSL connection. E.g.:     

```
BLA_TEST=EXPIRED; Expires=Sun, 26-Sep-2010 06:05:00 GMT; Path=/mail; Secure 
```

Of course this only makes sense when connecting via https...

**Comment by dound** [comment]
Specifying the `Secure` attribute on a cookie is important if you only want the user to send it over a secure connection.  Unfortunately, I don't think a sessions library can generally determine when this attribute is needed.

Since this decision needs to be made by the developer, gae-sessions could certainly present a configuration option for this.  Better yet, perhaps the developer could override this configuration option by explicitly specifying whether or not the session should be confined to a secure channel (e.g., an extra parameter to `Session.start()`).  

This wouldn't be too hard to implement - just add an extra attribute `secure` to the session (like `sid`), and populate it with the above methods (for a new session) or based on whether or not the `Secure` attribute was included on the incoming coming (for existing sessions).  Then when sending a cookie to the client, just include the `Secure` attribute based on the session's `secure` attribute.

Thanks for the idea!

**Comment by dound** [comment]
I'll release v1.05 with this functionality soon.  (All that is left to do is figure out the best way to determine whether the `Secure` attribute is set on clients the cookie sends us or not; unfortunately, `SimpleCookie` doesn't seem to provide this functionality).

**Comment by dound** [comment]
I've pushed a new, temporary branch which contains a prelease of v1.05 which adds this functionality.  The new branch passes all of the old tests, but I haven't had a chance to test the new functionality.

Once I get a chance to test the new "SSL only" option, I'll merge this new functionality into the master branch and officially release v1.05.

**Comment by msmart** [comment]
Great to hear. Glad I could be of help. I'll test it in the coming weeks.

**Comment by dound** [comment]
[v1.05](http://github.com/dound/gae-sessions/tree/v1.05) has been released.  The [release notes](http://github.com/dound/gae-sessions/wiki) credit you for this suggestion - thanks again!
