### ISSUE TITLE
I got a except. I don't know why? I need your help. 

### ISSUE THREAD

**Issue by qhm123** [dound/gae-sessions#11]
I just run the demo-with-google-logins but it failed. I use windows7 and Google app engine launcher.

File "D:\Website\dound-gae-sessions-26bd298\demo-with-google-logins\gaesessions__init__.py", line 414, in **init**
    raise ValueError("RFC2104 recommends you use at least a 32 character key.  Try os.urandom(64) to make a key.")
ValueError: RFC2104 recommends you use at least a 32 character key.  Try os.urandom(64) to make a key.

**Comment by dound** [comment]
In appengine_config.py, there is a variable named `COOKIE_KEY`.  You need to give a secret value so that it the sessions library can securely sign your cookies so that they cannot be tampered with.  To construct this secret value, I recommend you open the Python interpreter and run 'import os; os.urandom(64)' and use the output from that as the secret value.

**Comment by qhm123** [comment]
Oh, Thank you.
