### ISSUE TITLE
Extending session lifetime

### ISSUE THREAD

**Issue by tsuro** [dound/gae-sessions#21]
Is it possible to have a session.extend() function that extends the expiration of the session with default: the default lifetime to the current session or otherwise accepting a timedelta as the new extension.

**Comment by dound** [comment]
You can use the [`regenerate_id()`](http://dound.com/myprojects/gae-sessions/docs/html/docindex.html#gaesessions.Session.regenerate_id) method for this purpose.  You can optionally pass an `expiration_ts` parameter to the method (which allows you to control how long the new session will live).

This also modifies the session ID, but since the expiration time is encoded into the session ID there's no way around this anyway.
