### ISSUE TITLE
How to set expire time value 0

### ISSUE THREAD

**Issue by Grisson** [dound/gae-sessions#25]
Hi there,

could anybody tell  me how to set the expire time to 0(session cookie)? Latest commit added support of expire time value 0. But it does not mention how to use that feature. I have tired 
app = SessionMiddleware(app, cookie_key=COOKIE_KEY, lifetime=datetime.timedelta(0)) which does not work.

Thanks

**Comment by dound** [comment]
There isn't a way to configure the middleware to make all sessions default to having no expiration time.  To make a session have no expiration time, just call [`start`](http://dound.com/myprojects/gae-sessions/docs/html/docindex.html#gaesessions.Session.start) with the `expiration_ts` parameter set to 0.

Alternatively, you could tweak the implementation of `__make_sid` so that it sets the default expiration time to 0 if `self.lifetime` is `None` (and then pass `lifetime=None` as part of your middleware configuration).

**Comment by Grisson** [comment]
Thanks for your tip. I decide to change the __make_sid method. 
Do you think it is possible to add that into your code?

**Comment by dound** [comment]
If you make a pull request, I'll consider adding it.  For now, I'm going to leave it as-is (I'm not sure sessions which never expire are great from a security standpoint anyway).

**Comment by Grisson** [comment]
In fact, I use it as session cookie not a persistent cookie.
