### ISSUE TITLE
Session ID value is too long!

### ISSUE THREAD

**Issue by hungsimol** [dound/gae-sessions#7]
PHP session id: e8a54701d4551b8762b8add875a552c4 <-- 32

gae-sessions DgU00 id:
"4jJlnuj3/6dqxnAHthD2rpxoyiJLG/r2oxl2XwzFw+0=1281681340_d6ef1ccc2ffd341c70daed2c2026c796gAJ9cQBVAm1lcQEoY2dvb2dsZS5hcHBlbmdpbmUuZGF0YXN0b3JlLmVudGl0eV9wYgpFbnRpdHlQcm90bwpxAm9xA1W5ajFqDGh1bmdzaW1vbDAwMnIhCxIGTXlVc2VyIhUxMDk4MTIzNjgzNTA1MzQzNDk0NzAMchcaD3Bhc3Rfdmlld19jb3VudCAAKgIIBXJHGgR1c2VyIAAqPUNKE2h1bmdzaW1vbEBnbWFpbC5jb21SCWdtYWlsLmNvbZABAJoBFTEwOTgxMjM2ODM1MDUzNDM0OTQ3MESCASELEgZNeVVzZXIiFTEwOTgxMjM2ODM1MDUzNDM0OTQ3MAxxBWJzfXEGVQVwdnNsaXEHSwpzhnEILg==" <-- 459

Is it necessary? 

Security? I don't think so. "Man-in-the-middle attack" can get header information.

**Comment by dound** [comment]
I agree with you - making keys absurdly long is pointless.  Beyond a certain point, they aren't realistic to guess anymore.  And man-in-the-middle attacks are always a problem when operating over HTTP.

However, gae-sessions session IDs are exactly the same length as the PHP session ID you mentioned - 32 bytes.

The reason the cookie you copied is longer than this is because it includes not only the sesion ID, but also the session data - gae-sessions stores session data in cookies as long as it is sufficiently small.  This ends up being a lot faster than storing sessions in the datastore (or even memcache!).  If you'd rather have small cookies, just disable cookie-only sessions.

**Comment by hungsimol** [comment]
Thank you so much. How to disable cookie-only session?

"DEFAULT_COOKIE_ONLY_THRESH = 0"

> 8xUEG7Gw/qgywGTbjis06lfAAHZkfcVRINLmH1l9L0U=1281766952_d5c36a0fc33bdb7a12b7ec063cc22e6c
> <- 87

**Comment by dound** [comment]
You're welcome.  You can also disable cookie-only sessions by passing `cookie_only_threshold=0` to the SessionMiddleware constructor when you initialize it (and then you don't have to modify the gae-sessions source, though your solution works perfectly fine too).
